<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Equipo;

class EquiposSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Equipo::create(['nombre' =>'dB Technologies Opera 12', 'caracteristicas' => 'Amplificador digital de 600W 1200W / Pico, 600W / RMS SPL máximo de 129dB', 'precio' => '235', 'fotos' => 'https://sonicolor.es/5917-medium_default/db-technologies-opera-10-altavoz-amplificado.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'HK AUDIO SONAR 112 Xi', 'caracteristicas' => 'Caja acústica activa con woofer de 12" pulgadas y controlador HF de alto rendimineto de 1" pulgada, dispone de DSP de 24 bits con pantalla a color en su parte trasera para un cómodo control del menú en el cual se puede seleccionar 3 modos de sonido (Live, DJ, Monitor) de ecualización. Además tienes la posibilidad de conectar dos entradas de micrófono / linea con ecualizador de 3 bandas y HPF sintonizable, Aux In más canal Bluetooth con ecualizador de 3 bandas, Bluetooth 5.0 para transmisión de audio de mayor alcance y control remoto. Bluetooth TWS (True Wireless Stereo) para transmisión de audio estéreo con 2 modelos XI, y con aplicación de control remoto para iOS y Android. Muy versátil para su instalación y uso gracias a sus 3 puntos de montaje integrados M10, y montaje en poste de 35 mm con ángulo de inclinación ajustable de 0º a 7,5º. Fabricado en plástico muy robusta, de baja resonancia y ligera, y rejilla frontal de metal resistente con respaldo de espuma acústica negra.', 'precio' => '80', 'fotos' => 'https://sonicolor.es/43607-medium_default/hk-audio-sonar-112-xi.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'Micrófono Inalámbrico SHURE BLX288/PG58 Dual', 'caracteristicas' => 'Con 2 Micrófonos de Mano PG58, 2 clips para micrófonos, fuente de alimentación, 4 baterías AA, y guía de usuario. El Sistema Inalámbrico de Doble Canal con Dos Micrófonos de Mano BLX288/PG58 es parte de los sistemas inalámbricos BLX®. Los Sistemas Inalámbricos BLX de Shure combinan un sonido de calidad profesional con una fácil configuración y una interface intuitiva, para lograr el legendario sonido y rendimiento de Shure, directamente de la caja. Construidos con precisión y disponibles en una variedad de configuraciones, es la manera más accesible de dominar el escenario. El Microfono Inalámbrico Shure blx288/pg58 no parara de sorprenderte.', 'precio' => '50', 'fotos' => 'https://sonicolor.es/8861-large_default/shure-blx288_pg58-microfono-inalambrico-de-mano.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'Maquina Humo', 'caracteristicas' => 'Capacidad de calentamiento de 1300W, Incluye unidad de control remoto por cable y control remoto inalámbrico', 'precio' => '35', 'fotos' => 'https://thumbs.static-thomann.de/thumb/padthumb600x600/pics/bdb/403498/11733600_800.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'Tarimas', 'caracteristicas' => 'Tarima para teatro, conciertos, espectaculos, etc... de fácil utilización.', 'precio' => '100', 'fotos' => 'https://www.hermex.es/media/images/articulos/large/1_4892.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'BEHRINGER MOVING HEAD MH363', 'caracteristicas' => 'La cabeza móvil MH363 de Behringer es un modelo formado por 36 leds de 3W de potencia en colores RGBW con una potencia total de 108W procedente de sus 12 leds rojos, verdes y azules. Behringer ha puesto todo su esmero en crear un producto valido para multitud de ocasiones, ya sea para discotecas y salas de eventos como para exposiciones y actuaciones gracias a su nulo ruido de movimiento y configuración de iluminación.', 'precio' => '45', 'fotos' => 'https://sonicolor.es/17925-large_default/behringer-moving-head-mh363.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'WORK Pro LS-1 Mesa digital de iluminación', 'caracteristicas' => 'La WORK Pro LS-1 es una mesa digital de control de iluminación multiplataforma con hasta 8 universos DMX, con una superficie de control intuitiva y ergonómica. La LS-1 integra 4 encoders, 10 master playbacks y una pantalla a color con una Interfaz de Usuario ultra rápida basada en Web, y que permite conectar hasta 3 dispositivos simultáneamente para crear tu propio sistema de control, sin importar el Sistema Operativo utilizado (iOS, Android, Linux, Windows, macOS). LightShark establece con todo ello un nuevo concepto en control de iluminación, y es una herramienta ideal para nightclubs, DJ´s, eventos corporativos y de medio tamaño, escuelas, iglesias, etc. LS-1 dispone, en su parte posterior, de un soporte para dispositivos como tablets, además de una entrada de carga USB situada en su panel trasero, que permite cargar los dispositivos asociados en todo momento.', 'precio' => '120', 'fotos' => 'https://sonicolor.es/8232-large_default/work-pro-ls-1.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'BEHRINGER DIAMOND DOME DD610', 'caracteristicas' => 'El nuevo efecto LED de Behringer, DD610, será un top ventas para pequeños eventos y fiestas caseras sin duda. Con un multimodo y color RGBWA a través de un LED esta bola de efecto le pondrá el toque necesario para iluminar y animar tus fiestas. Formado por 1 led 6en1 contiene los colores Rojo, Verde, Azul, Blando, Ambar y UV los cuales se fusionan y rotan mediante un efecto estroboscópico y dimmer a través de su carcasa en forma de diamante especialmente diseñada para ayudar a expandir la luz.', 'precio' => '20', 'fotos' => 'https://sonicolor.es/17924-large_default/behringer-diamond-dome-dd610.jpg', 'disponible' => 0]);
        Equipo::create(['nombre' =>'Máquina de Confetti Showtec FX SHOT MKII 60906', 'caracteristicas' => 'El Showtec FX Shot MKII es un disparador de confeti eléctrico muy fácil de utilizar. Está diseñado para disparar cañones eléctricos prellenados de un solo uso, disponibles en tamaños de 50 y 80°cm. Se puede elegir entre confeti o serpentinas de varios colores, incluyendo fluorescente, UV y metálico. Los cañones contienen una cápsula presurizada de nitrógeno que lanza confeti a una distancia de hasta 12°m, 20°m para las serpentinas.', 'precio' => '60', 'fotos' => 'https://sonicolor.es/6944-large_default/showtec-confetti-fx-shot-mkii-maquina-60906.jpg', 'disponible' => 0]);
    }
}